<?php

$GLOBALS['uwwtd_map']['maps']=[
    //===Compliance
    //==MS Level
    'mslevel_global_comp_10th'=>['title'=>"Degree of compliance at MS level for 10th report (2016)", 'map_scale'=>'MS Level', 'map_type'=>'Compliance at MS level', 'access'=>true],
    'mslevel_art3_comp_10th'=>['title'=>"Degree of compliance with Article 3 at MS level for 10th report (2016)", 'map_scale'=>'MS Level', 'map_type'=>'Compliance at MS level', 'access'=>true],
    'mslevel_art4_comp_10th'=>['title'=>"Degree of compliance with Article 4 at MS level for 10th report (2016)", 'map_scale'=>'MS Level', 'map_type'=>'Compliance at MS level', 'access'=>true],
    'mslevel_art5_comp_10th'=>['title'=>"Degree of compliance with Article 5 at MS level for 10th report (2016)", 'map_scale'=>'MS Level', 'map_type'=>'Compliance at MS level', 'access'=>true],
    //==NUTS 2
    'nuts2level_global_comp_10th_by_cc'=>['title'=>"Degree of compliance at Nuts 2 level for 10th report (2016) by country", 'map_scale'=>'Nuts 2', 'map_type'=>'Compliance at Nuts 2 level', 'access'=>false],
    'nuts2level_global_comp_10th_by_cc_mono'=>['title'=>"Compliance rate at Nuts 2 level for 10th report (2016) by country", 'map_scale'=>'Nuts 2', 'map_type'=>'Compliance at Nuts 2 level monochrome', 'access'=>false],
    'nuts2level_global_comp_10th_mono'=>['title'=>"Compliance rate at Nuts 2 level for 10th report (2016)", 'map_scale'=>'Nuts 2', 'map_type'=>'Compliance at Nuts 2 level monochrome', 'access'=>false],
    'nuts2level_global_comp_10th'=>['title'=>"Degree of compliance at Nuts 2 level for 10th report (2016)", 'map_scale'=>'Nuts 2', 'map_type'=>'Compliance at Nuts 2 level', 'access'=>true],
    'nuts2level_art3_comp_10th'=>['title'=>"Degree of compliance with Article 3 at Nuts 2 level for 10th report (2016)", 'map_scale'=>'Nuts 2', 'map_type'=>'Compliance at Nuts 2 level', 'access'=>true],
    'nuts2level_art4_comp_10th'=>['title'=>"Degree of compliance with Article 4 at Nuts 2 level for 10th report (2016)", 'map_scale'=>'Nuts 2', 'map_type'=>'Compliance at Nuts 2 level', 'access'=>true],
    'nuts2level_art5_comp_10th'=>['title'=>"Degree of compliance with Article 5 at Nuts 2 level for 10th report (2016)", 'map_scale'=>'Nuts 2', 'map_type'=>'Compliance at Nuts 2 level', 'access'=>true],
    //== RBD
    'rbdlevel_global_comp_10th'=>['title'=>"Degree of compliance at RBD level for 10th report (2016)", 'map_scale'=>'RBD', 'map_type'=>'Compliance at RBD level', 'access'=>true],
    'rbdlevel_art3_comp_10th'=>['title'=>"Degree of compliance with Article 3 at RBD level for 10th report (2016)", 'map_scale'=>'RBD', 'map_type'=>'Compliance at RBD level', 'access'=>true],
    'rbdlevel_art4_comp_10th'=>['title'=>"Degree of compliance with Article 4 at RBD level for 10th report (2016)", 'map_scale'=>'RBD', 'map_type'=>'Compliance at RBD level', 'access'=>true],
    'rbdlevel_art5_comp_10th'=>['title'=>"Degree of compliance with Article 5 at RBD level for 10th report (2016)", 'map_scale'=>'RBD', 'map_type'=>'Compliance at RBD level', 'access'=>true],
    
    //===Distance To Target
    //==MS Level
    'mslevel_art3_dtt_10th'=>['title'=>"Degree of distance to target with Article 3 at MS level for 10th report (2016)", 'map_scale'=>'MS Level', 'map_type'=>'Distance to target at MS level', 'access'=>true],
    'mslevel_art4_dtt_10th'=>['title'=>"Degree of distance to target with Article 4 at MS level for 10th report (2016)", 'map_scale'=>'MS Level', 'map_type'=>'Distance to target at MS level', 'access'=>true],
    'mslevel_art5_dtt_10th'=>['title'=>"Degree of distance to target with Article 5 at MS level for 10th report (2016)", 'map_scale'=>'MS Level', 'map_type'=>'Distance to target at MS level', 'access'=>true],
    //==NUTS 2
    'nuts2level_art3_dtt_10th'=>['title'=>"Degree of distance to target with Article 3 at Nuts 2 level for 10th report (2016)", 'map_scale'=>'Nuts 2', 'map_type'=>'Distance to target at Nuts 2 level', 'access'=>true],
    'nuts2level_art4_dtt_10th'=>['title'=>"Degree of distance to target with Article 4 at Nuts 2 level for 10th report (2016)", 'map_scale'=>'Nuts 2', 'map_type'=>'Distance to target at Nuts 2 level', 'access'=>true],
    'nuts2level_art5_dtt_10th'=>['title'=>"Degree of distance to target with Article 5 at Nuts 2 level for 10th report (2016)", 'map_scale'=>'Nuts 2', 'map_type'=>'Distance to target at Nuts 2 level', 'access'=>true],
    //== RBD
    'rbdlevel_art3_dtt_10th'=>['title'=>"Degree of distance to target with Article 3 at RBD level for 10th report (2016)", 'map_scale'=>'RBD', 'map_type'=>'Distance to target at RBD level', 'access'=>true],
    'rbdlevel_art4_dtt_10th'=>['title'=>"Degree of distance to target with Article 4 at RBD level for 10th report (2016)", 'map_scale'=>'RBD', 'map_type'=>'Distance to target at RBD level', 'access'=>true],
    'rbdlevel_art5_dtt_10th'=>['title'=>"Degree of distance to target with Article 5 at RBD level for 10th report (2016)", 'map_scale'=>'RBD', 'map_type'=>'Distance to target at RBD level', 'access'=>true],
    
    //SA
    'country_bg,sa_other_10th,csa_10th,sa_tw_10th,sa_coast_10th,sa_rw_10th,sa_rwp_10th,country_bd'=>['title'=>"Overview of designated Sensitive Areas, Catchment of Sensitive Areas and the application of Article 5(8) UWWTD in European Union", 'map_scale'=>'MS Level', 'map_type'=>'Sensitive Area', 'access'=>true],
];
$GLOBALS['uwwtd_map']['legend']=[
    'Sensitive Area'=>[
        [
            'title'=>'',
            'items'=>[
                ['label'=>'Sensitive areas (MS applies Art 5(2-3))', 'color'=>'#4b8400'],
                ['label'=>'Catchment of sensitive areas (MS applies Art 5(2-3))', 'color'=>'#a4d596'],
                ['label'=>'Sensitive area (MS applies Art 5(2-3) and Art 5(8))', 'color'=>' #969664'],
            ]
        ],
        [
            'title'=>'',
            'items'=>[
                ['label'=>'Sensitive area (MS applies Art 5(4) and Art 5(8))', 'color'=>'#3f348e'],
                ['label'=>'Sensitive area (MS applies Art 5(4))', 'color'=>'#654aa9'],
                ['label'=>'Normal areas', 'color'=>'#faf8cc'], //#ddf7b4
                ['label'=>'Non EU countries', 'color'=>'#ececec'],
            ]
        ]
    ],
    'Compliance at MS level'=>[
        [
            'title'=>'Degree of compliance',
            'items'=>[
                ['label'=>'97-100 %', 'color'=>'#2b83ba'],
                ['label'=>'95-97 %', 'color'=>'#75de5d'],
                ['label'=>'85-95 %', 'color'=>'#f0f018'],
                ['label'=>'70-85 %', 'color'=>'#fdae61'],
                ['label'=>'0-70 %', 'color'=>'#d7191c'],
            ]
        ],
        [
            'title'=>'',
            'items'=>[
                ['label'=>'Not Subject to compliance due to ongoing transitional period', 'color'=>'#808080'],
                ['label'=>'Non EU countries', 'color'=>'#ececec'],
            ]
        ]
    ],
    'Compliance at Nuts 2 level'=>[
        [
            'title'=>'Degree of compliance',
            'items'=>[
                ['label'=>'97-100 %', 'color'=>'#2b83ba'],
                ['label'=>'95-97 %', 'color'=>'#75de5d'],
                ['label'=>'85-95 %', 'color'=>'#f0f018'],
                ['label'=>'70-85 %', 'color'=>'#fdae61'],
                ['label'=>'0-70 %', 'color'=>'#d7191c'],
            ]
        ],
        [
            'title'=>'',
            'items'=>[
                ['label'=>'No data', 'color'=>'#ffffff'],
                ['label'=>'Compliance assesment on whole territory only', 'color'=>'#4b4b4b'],
                ['label'=>'Not Subject to compliance due to ongoing transitional period', 'color'=>'#808080'],
                ['label'=>'Non EU countries', 'color'=>'#ececec'],
            ]
        ]
    ],
    'Compliance at Nuts 2 level monochrome'=>[
        [
            'title'=>'Degree of compliance',
            'items'=>[
                ['label'=>'97-100 %', 'color'=>'#fce1ab'],
                ['label'=>'95-97 %', 'color'=>'#dc9a44'],
                ['label'=>'85-95 %', 'color'=>'#cf7e2d'],
                ['label'=>'70-85 %', 'color'=>'#be4a2a'],
                ['label'=>'0-70 %', 'color'=>'#a72023'],
            ]
        ],
        [
            'title'=>'',
            'items'=>[
                ['label'=>'No data', 'color'=>'#ffffff'],
                ['label'=>'Not Subject to compliance due to ongoing transitional period', 'color'=>'#808080'],
                ['label'=>'Non EU countries', 'color'=>'#ececec'],
            ]
        ]
    ],
    'Compliance at RBD level'=>[
        [
            'title'=>'Degree of compliance',
            'items'=>[
                ['label'=>'97-100 %', 'color'=>'#2b83ba'],
                ['label'=>'95-97 %', 'color'=>'#75de5d'],
                ['label'=>'85-95 %', 'color'=>'#f0f018'],
                ['label'=>'70-85 %', 'color'=>'#fdae61'],
                ['label'=>'0-70 %', 'color'=>'#d7191c'],
            ]
        ],
        [
            'title'=>'',
            'items'=>[
                ['label'=>'No data', 'color'=>'#ffffff'],
                ['label'=>'Compliance assesment on whole territory only', 'color'=>'#4b4b4b'],
                ['label'=>'Not Subject to compliance due to ongoing transitional period', 'color'=>'#808080'],
                ['label'=>'Non EU countries', 'color'=>'#ececec'],
            ]
        ]
    ],
    'Distance to target at MS level'=>[
        [
            'title'=>'Degree of distance to target',
            'items'=>[
                ['label'=>'0-3 %', 'color'=>'#2b83ba'],
                ['label'=>'3-5 %', 'color'=>'#75de5d'],
                ['label'=>'5-15 %', 'color'=>'#f0f018'],
                ['label'=>'15-30 %', 'color'=>'#fdae61'],
                ['label'=>'30-100 %', 'color'=>'#d7191c'],
            ]
        ],
        [
            'title'=>'',
            'items'=>[
                ['label'=>'Not Subject to compliance due to ongoing transitional period', 'color'=>'#808080'],
                ['label'=>'Non EU countries', 'color'=>'#ececec'],
            ]
        ]
    ],
    'Distance to target at Nuts 2 level'=>[
        [
            'title'=>'Degree of distance to target',
            'items'=>[
                ['label'=>'0-3 %', 'color'=>'#2b83ba'],
                ['label'=>'3-5 %', 'color'=>'#75de5d'],
                ['label'=>'5-15 %', 'color'=>'#f0f018'],
                ['label'=>'15-30 %', 'color'=>'#fdae61'],
                ['label'=>'30-100 %', 'color'=>'#d7191c'],
            ]
        ],
        [
            'title'=>'',
            'items'=>[
                ['label'=>'No data', 'color'=>'#ffffff'],
                ['label'=>'Compliance assesment on whole territory only', 'color'=>'#4b4b4b'],
                ['label'=>'Not Subject to compliance due to ongoing transitional period', 'color'=>'#808080'],
                ['label'=>'Non EU countries', 'color'=>'#ececec'],
            ]
        ]
    ],
    'Distance to target at RBD level'=>[
        [
            'title'=>'Degree of distance to target',
            'items'=>[
                ['label'=>'0-3 %', 'color'=>'#2b83ba'],
                ['label'=>'3-5 %', 'color'=>'#75de5d'],
                ['label'=>'5-15 %', 'color'=>'#f0f018'],
                ['label'=>'15-30 %', 'color'=>'#fdae61'],
                ['label'=>'30-100 %', 'color'=>'#d7191c'],
            ]
        ],
        [
            'title'=>'',
            'items'=>[
                ['label'=>'No data', 'color'=>'#ffffff'],
                ['label'=>'Compliance assesment on whole territory only', 'color'=>'#4b4b4b'],
                ['label'=>'Not Subject to compliance due to ongoing transitional period', 'color'=>'#808080'],
                ['label'=>'Non EU countries', 'color'=>'#ececec'],
            ]
        ]
    ]
];

$GLOBALS['uwwtd_map']['europe'] = array(
  'wkhtmlpath_command' => "/opt/wkhtmltox.0.12.4/bin/wkhtmltoimage --crop-y 10 --crop-w 700 --crop-h 1170 --javascript-delay 14000 '[#SOURCE#]' [#TARGET#]",
  'url_source' => url('map/europe'),
  'main_map' => 'uwwtd_map_europe',
  'list_minimap' =>   array(
    
    'topleft' => array(
      //Açores  PT
      'Açores (PT)' => array(
        'title' => 'Açores (PT)',
        'map_name' => 'acore',
        'class'    => 'acore',
      ),
      //MAdeira  PT
      'Madeira (PT)' => array(
        'title' => 'Madeira (PT)',
        'map_name' => 'madeira',
        'class'    => 'madeira',
      ),
  
      //Islas Canriass  ES
      'Islas Canarias (ES)' => array(
        'title' => 'Islas Canarias (ES)',
        'map_name' => 'canariass',
        'class'    => 'canariass',
      ),
    ),

    'topright' => array(
      //FR
      'Guyane (FR)' => array(
        'title' => 'Guyane (FR)',
        'map_name' => 'guyane',
        'class'    => 'guyane',
      ),
      'Martinique (FR)' => array(
        'title' => 'Martinique (FR)',
        'map_name' => 'martinique',
        'class'    => 'martinique',
      ),
      'Guadeloupe (FR)' => array(
        'title' => 'Guadeloupe (FR)',
        'map_name' => 'guadeloupe',
        'class'    => 'guadeloupe',
      ),
       'Saint Martin (FR)' => array(
        'title' => 'Saint Martin (FR)',
        'map_name' => 'stmartin',
        'class'    => 'stmartin',
      ),
      
      'La Réunion (FR)' => array(
        'title' => 'La Réunion (FR)',
        'map_name' => 'reunion',
        'class'    => 'reunion',
      ),
      'Mayotte (FR)' => array(
        'title' => 'Mayotte (FR)',
        'map_name' => 'mayotte',
        'class'    => 'mayotte',
      ),
    ),

    'bottomleft' => array(
      //Malta 
      'Malta' => array(
        'title' => 'Malta',
        'map_name' => 'malta',
        'class'    => 'malta',
      ),
    ),
  ),
);